# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a160b5b3a2b29963a60b18305bff361c6da899cb4faa9644cf514e943e053fe1c927b4491c0cbd0807b22b27363b465e95618ba49b18f777e39e7f49860d4475

test:
  secret_key_base: e5404c9ed305487e1f57ad6e474e61ab2518e773a110a05e8bc9ff9fc8cd0451529123b9d2e0423c049a6d1aa5020a4544461769a6c205c684d33b925cf775e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
